# Generated by Django 5.2.15 on 2026-07-03 22:30

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('nickname', models.CharField(blank=True, max_length=60)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('sms', 'SMS'), ('telegram', 'Telegram')], max_length=20)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=60)),
                ('is_preferred', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('organizer', 'Organizer-entered'), ('guest_requested', 'Guest-requested')], default='organizer', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('proposed', 'Proposed (awaiting approval)')], default='active', max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='core.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('location_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('host_display', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('allow_plus_ones', models.BooleanField(default=True)),
                ('plus_ones_cap', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('show_guest_list', models.BooleanField(default=False)),
                ('ics_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.household'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=core.models.make_token, editable=False, max_length=64, unique=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('shared', 'Shared'), ('opened', 'Opened'), ('responded', 'Responded'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('plus_ones', models.PositiveSmallIntegerField(default=0)),
                ('latest_note', models.TextField(blank=True)),
                ('latest_note_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.contact')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.event')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.household')),
                ('send_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.contactchannel')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('sms', 'SMS'), ('telegram', 'Telegram')], max_length=20)),
                ('address_used', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('shared', 'Shared'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.contactchannel')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.invitation')),
            ],
        ),
        migrations.AddField(
            model_name='contactchannel',
            name='requested_via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_requests', to='core.invitation'),
        ),
        migrations.CreateModel(
            name='InvitationAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rsvp_status', models.CharField(choices=[('no_reply', 'No reply'), ('going', 'Going'), ('maybe', 'Maybe'), ('cant', "Can't")], default='no_reply', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_records', to='core.contact')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='core.invitation')),
            ],
        ),
        migrations.CreateModel(
            name='RsvpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('no_reply', 'No reply'), ('going', 'Going'), ('maybe', 'Maybe'), ('cant', "Can't")], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('actor', models.CharField(choices=[('guest', 'Guest'), ('organizer', 'Organizer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.invitationattendee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='core.tag'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'starts_at'], name='core_event_status_d39a79_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['state'], name='core_invita_state_537d90_idx'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contact__isnull', False), ('household__isnull', True)), models.Q(('contact__isnull', True), ('household__isnull', False)), _connector='OR'), name='invitation_contact_xor_household'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('contact__isnull', False)), fields=('event', 'contact'), name='one_invitation_per_event_contact'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('household__isnull', False)), fields=('event', 'household'), name='one_invitation_per_event_household'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='core_delive_status_d4973b_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactchannel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_preferred', True)), fields=('contact',), name='one_preferred_channel_per_contact'),
        ),
        migrations.AddConstraint(
            model_name='invitationattendee',
            constraint=models.UniqueConstraint(fields=('invitation', 'contact'), name='one_attendee_row_per_person'),
        ),
        migrations.AddIndex(
            model_name='rsvpevent',
            index=models.Index(fields=['attendee', 'created_at'], name='core_rsvpev_attende_0ae4dc_idx'),
        ),
    ]
