# Generated by Django 5.2.15 on 2026-07-06 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_poll_polloption_pollvote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('reply_email', models.EmailField(blank=True, max_length=254)),
                ('page_path', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('handled', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='core.event')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='core.invitation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
