# Generated by Django 5.2.15 on 2026-07-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='primary_contact',
        ),
    ]
